version: "3.9"

services:
  web:
    build: .
    container_name: web_footlocker
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: db_footlocker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: footlocker
    volumes:
      - db_data:/var/lib/mysql
      - ./db/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - app_network

volumes:
  db_data:

networks:
  pr1_network: